// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Book struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Isbn  string `json:"isbn"`
}

func (Book) IsEntity() {}
