// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Media interface {
	IsMedia()
	GetID() string
}

type Author struct {
	Name  string  `json:"name"`
	Media []Media `json:"media,omitempty"`
}

type Book struct {
	ID string `json:"id"`
}

func (Book) IsEntity() {}

type BookMedia struct {
	ID    string `json:"id"`
	Media *Book  `json:"media"`
}

func (BookMedia) IsMedia()           {}
func (this BookMedia) GetID() string { return this.ID }

type Movie struct {
	ID string `json:"id"`
}

func (Movie) IsEntity() {}

type MovieMedia struct {
	ID    string `json:"id"`
	Media *Movie `json:"media"`
}

func (MovieMedia) IsMedia()           {}
func (this MovieMedia) GetID() string { return this.ID }
