package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"

	"github.com/Dennor/graphql-go-tools-bad-resolution/books/graph/model"
	"golang.org/x/exp/slices"
)

// FindBookByID is the resolver for the findBookByID field.
func (r *entityResolver) FindBookByID(ctx context.Context, id string) (*model.Book, error) {
	idx := slices.IndexFunc(books, func(m *model.Book) bool {
		return m != nil && m.ID == id
	})
	if idx == -1 {
		return nil, nil
	}
	return books[idx], nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
